# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(512, 327)
        self.formLayout_2 = QtWidgets.QFormLayout(Dialog)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.separatorFieldComboBox = QtWidgets.QComboBox(Dialog)
        self.separatorFieldComboBox.setObjectName("separatorFieldComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.separatorFieldComboBox)
        self.processButton = QtWidgets.QPushButton(Dialog)
        self.processButton.setObjectName("processButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.processButton)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.parentDeckLineEdit = QtWidgets.QLineEdit(Dialog)
        self.parentDeckLineEdit.setObjectName("parentDeckLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.parentDeckLineEdit)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.deckChooser = QtWidgets.QWidget(Dialog)
        self.deckChooser.setObjectName("deckChooser")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deckChooser)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.separatorFieldComboBox, self.processButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "Separator field"))
        self.processButton.setText(_translate("Dialog", "Process"))
        self.label.setText(_translate("Dialog", "Parent deck"))
        self.label_2.setText(_translate("Dialog", "Deck"))
